{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Accuracy: 1.0\n",
      "\n",
      "Prediction:\n",
      "The probability of drought in Goa for the given average rainfall of 2.00 mm is 1.0000.\n"
     ]
    }
   ],
   "source": [
    "# Import necessary libraries\n",
    "import pandas as pd\n",
    "import calendar\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import accuracy_score, classification_report\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.utils import resample\n",
    "\n",
    "# File paths for datasets\n",
    "file_paths = {\n",
    "    'Kolkata': 'Kolkata.csv',\n",
    "    'Goa': 'Goa.csv',\n",
    "    'Meghalaya': 'Meghalaya.csv',\n",
    "    'Mizoram': 'Mizoram.csv'\n",
    "}\n",
    "\n",
    "# Load and combine datasets\n",
    "dataframes = {location: pd.read_csv(path) for location, path in file_paths.items()}\n",
    "\n",
    "# Function to preprocess individual datasets\n",
    "def preprocess_dataset(df, location):\n",
    "    # Handle missing values\n",
    "    df['Average'] = df['Average'].fillna(df['Average'].mean())\n",
    "    \n",
    "    # Add a location column to differentiate data\n",
    "    df['Location'] = location\n",
    "\n",
    "    # Add drought classification\n",
    "    drought_threshold = 3.0\n",
    "    df['Drought'] = df['Average'].apply(lambda x: 1 if x < drought_threshold else 0)\n",
    "    \n",
    "    return df\n",
    "\n",
    "# Preprocess all datasets\n",
    "processed_dataframes = {loc: preprocess_dataset(df.copy(), loc) for loc, df in dataframes.items()}\n",
    "combined_data = pd.concat(processed_dataframes.values(), ignore_index=True)\n",
    "\n",
    "# Debug: Check class distribution\n",
    "# print(\"\\nClass Distribution Before Resampling:\")\n",
    "# print(combined_data['Drought'].value_counts(normalize=True))\n",
    "\n",
    "# Upsample minority class to handle imbalance\n",
    "majority = combined_data[combined_data['Drought'] == 0]\n",
    "minority = combined_data[combined_data['Drought'] == 1]\n",
    "minority_upsampled = resample(minority, replace=True, n_samples=len(majority), random_state=42)\n",
    "\n",
    "balanced_data = pd.concat([majority, minority_upsampled])\n",
    "\n",
    "# Debug: Check class distribution after balancing\n",
    "# print(\"\\nClass Distribution After Resampling:\")\n",
    "# print(balanced_data['Drought'].value_counts(normalize=True))\n",
    "\n",
    "# Prepare features and target\n",
    "X = balanced_data[['Average']]\n",
    "y = balanced_data['Drought']\n",
    "\n",
    "# Split data into training and test sets\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "# Scale the features\n",
    "scaler = StandardScaler()\n",
    "X_train = scaler.fit_transform(X_train)\n",
    "X_test = scaler.transform(X_test)\n",
    "\n",
    "# Train a Random Forest model\n",
    "model = RandomForestClassifier(random_state=42, class_weight=\"balanced\", n_estimators=100)\n",
    "model.fit(X_train, y_train)\n",
    "\n",
    "# Make predictions\n",
    "y_pred = model.predict(X_test)\n",
    "\n",
    "# Evaluate the model\n",
    "accuracy = accuracy_score(y_test, y_pred)\n",
    "classification_rep = classification_report(y_test, y_pred, zero_division=1)\n",
    "\n",
    "# print(\"\\nModel Evaluation:\")\n",
    "print(\"Accuracy:\", accuracy)\n",
    "# print(\"Classification Report:\\n\", classification_rep)\n",
    "\n",
    "# Prediction function for user input with probability\n",
    "def predict_drought(location, avg_rainfall):\n",
    "    if location not in file_paths.keys():\n",
    "        return f\"Invalid location: {location}. Available locations are {list(file_paths.keys())}.\"\n",
    "    \n",
    "    # Prepare the input sample\n",
    "    sample = pd.DataFrame({'Average': [avg_rainfall]})\n",
    "    scaled_sample = scaler.transform(sample)\n",
    "    \n",
    "    # Predict drought probabilities\n",
    "    prob = model.predict_proba(scaled_sample)\n",
    "    drought_probability = prob[0][1]  # Probability of class 1 (drought)\n",
    "    \n",
    "    return f\"The probability of drought in {location} for the given average rainfall of {avg_rainfall:.2f} mm is {drought_probability:.4f}.\"\n",
    "\n",
    "# Example usage\n",
    "location_to_predict = \"Goa\"\n",
    "average_rainfall_to_predict = 2  # Example average rainfall value\n",
    "\n",
    "print(\"\\nPrediction:\")\n",
    "print(predict_drought(location_to_predict, average_rainfall_to_predict))\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
